### PR TITLE
_projects: disable WATCHDOG in projects

### PR DESCRIPTION
**Pull request by anglov**
JIRA: DEND-32

## Description

Disable WATCHDOG explicitly, which will be included in phoenix-rtos/phoenix-rtos-build#163
Currently nothing refreshing watchdog in phoenix-rtos-project.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: armv7m4-stm32l4x6-nucleo.
It would be great if someone could check this changes on armv7a7-im6ull-evk and arm7m7-imxrt117x-evk

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/847
https://github.com/phoenix-rtos/plo/pull/293
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/453
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/163
- [x] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
> Maybe it should be disabled by default on other platform too? imx6ull? imxrt106x?

I think it needs to be disabled for imx6ull-evk as the tests take 8min and nobody is kicking watchdog. 

Regarding kernel on stm32l* and rt10xx  - the watchdog is enabled only if NDEBUG (but we're building with DEBUG=1 on CI, so this change might not be necessary - but IMHO good to have it explicitly stated in project file (maybe we could add comment - "enable watchog at bootup if not debugging" or something similar)

**Comment by nalajcie** [comment]
aaaa, circular PR dependency!


image

**Comment by anglov** [comment]
> aaaa, circular PR dependency!

I just put relation chain here ;) 

Changes made.

**Review by agkaminski — DISMISSED** [review]

**Comment by anglov** [comment]
I accidentally remove new line in board_config.h - restored.

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
