### PR TITLE
_targets: stm32l4x6: Remove exported BOARD_CONFIG

### PR DESCRIPTION
**Pull request by anglov**
JIRA: DEND-32

## Description

Remove exported BOARD_CONFIG

## Motivation and Context

It overwrites board_config.h and make confusion. Not needed for internal project - rest of removal deprecated BOARD_CONFIG expoted variable removal will be performed in others commits. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Project that use fork of phoenix-rtos-project and use BOARD_CONFIG env variable, need to be switched to board_config.h 

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: armv7m4-stm32l4x6-nucleo.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/422
Updates submodules with that commit first
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
maybe we could also remove places where it's being appended to CFLAGS?

image

**Comment by anglov** [comment]
> maybe we could also remove places where it's being appended to CFLAGS?
> 
> image

Not yet please. I'am concerned about it and will do it when I have done everything in internal project.

**Comment by anglov** [comment]
Setting as draft as board_config.h is wrongly propagated in stm32l4-multi currently.
I thought that PR are independed but unfortunatelly - not.

**Comment by anglov** [comment]
Now it's good :)

**Pull request merged**
