### PR TITLE
update submodules

### PR DESCRIPTION
**Pull request by damianloew**
## Description

* libphoenix 4322d33...a514d66 (2):
  > stdio/format: Fix incorrect behaviour for NULL
  > strerr: Return error msg instead of NULL on invalid errnum

* phoenix-rtos-build 886a9e6...2a20c45 (3):
  > Build hostutils on host-generic-pc target
  > build.sh: abort build when PROJECT_PATH is not set
  > makes: fix local header dir being resolved to /include

* phoenix-rtos-corelibs 87f7e85...130658b (3):
  > storage: remove mabye-uninitialized GCC warning
  > ptable: Remove board_config.h dependency
  > libptable: remove linux host dependency

* phoenix-rtos-devices 6353bde...9d51724 (1):
  > storage: fix storage size checks

* phoenix-rtos-kernel 1b41faf...7a13135 (5):
  > ia32: hal_cpuFeatures() fixed the 'nx' feature check
  > hal/ia32: Fix reboot hanging on some hardware
  > hal/ia32: MISRA
  > hal/ia32: Enable FPU (with lazy ctx stacking)
  > threads: use const variable for pending queue wakeup

* phoenix-rtos-ports 102d827...0c5838e (3):
  > busybox: fix downloaded file check
  > busybox: add downloading from mirror on error
  > picocom: add compilation process

* phoenix-rtos-tests 4466a76...c13ef42 (21):
  > libc: scanf tests: add SANITIZE_ADDRESS detection and scanf output reset
  >  libc: scanf tests: add test groups for [], *, m and mixed specifiers
  > libc: scanf tests: add test groups for c, s, p, n specifiers
  > libc: scanf tests: add test groups for a, e, f, g specifiers
  > libc: scanf tests: add test groups for d, i, o, u, x specifiers
  > trunner: fix handling TEST_IGNORE_MESSAGE
  > strtod: add basic tests for strtod
  > unity: enable Double Precision
  > trunner: fix parsed unity result
  > libc: add funcions from ctype.h tests
  > runner: don't reboot to load apps on rootfs target
  > runner: include traceback in all error messages
  > runner: allow to specify test by yaml file
  > runner: pass ctx to harness
  > runner: add list type registration to extension
  > runner: add kwargs argument to cli
  > libc: change name convention
  > libc: enable malloc_usable_size
  > remove old test for env functions
  > libc: add test for env functions
  > libc: string.h: add len functions tests

* phoenix-rtos-utils 01e19c0...cf5de2c (1):
  > psh: Implement `ln` command

* plo 42bc591...dc68030 (2):
  > hal/ia32: Fix reboot hanging on some hardware
  > hal/ia32: Fix kernel not starting on some hardware

## Motivation and Context

JIRA: CI-193

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
@agkaminski do we want newest kernel in phoenix-rtos-project? I think it makes stabiility issues on `imx6ull` currently worse - can You advice which commit we should keep the kernel on for now?

**Comment by agkaminski** [comment]
I advise not to update for now

**Comment by nalajcie** [comment]
> I advise not to update for now

@damianloew  please remove `phoenix-rtos-kernel` update from this PR

**Comment by damianloew** [comment]
> > I advise not to update for now
> 
> @damianloew please remove `phoenix-rtos-kernel` update from this PR

As discussed with @agkaminski I've updated `phoenix-rtos-kernel` to the following commit: https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/d35fa5a7324eb52e77590c575eab36367be2d0e6

**Pull request merged**
