### PR TITLE
docker-build.sh: pass LONG_TEST variable

### PR DESCRIPTION
**Pull request by badochov**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by badochov** [comment]
Are there any other potentially missing env variables?

**Review by nalajcie — APPROVED** [review]

**Review by damianloew — COMMENTED** [review]
I think that `SYSPAGE` could be removed, but not necessarily within this PR

**Comment by nalajcie** [comment]
> I think that `SYSPAGE` could be removed, but not necessarily within this PR

`SYSPAGE` is needed if you want to modify syspage, eg. build ia32-generc-qemu with serial UART instead of `vga` (you need to pass `CONSOLE=serial SYSPAGE='psh pc-ata uart16550' TARGET=ia32-generic-qemu`).

Please don't remove anything.

**Comment by damianloew** [comment]
> > I think that `SYSPAGE` could be removed, but not necessarily within this PR
> 
> `SYSPAGE` is needed if you want to modify syspage, eg. build ia32-generc-qemu with serial UART instead of `vga` (you need to pass `CONSOLE=serial SYSPAGE='psh pc-ata uart16550' TARGET=ia32-generic-qemu`).
> 
> Please don't remove anything.



> uart16550

It seems that it's deprecated and no longer needed thanks to: https://github.com/phoenix-rtos/phoenix-rtos-project/blob/3cdb486e4276b9ac1fa8ff88e840c38d6939b665/_targets/build.project.ia32-generic#L65

Please correct me if I am wrong (setting CONSOLE=serial is sufficient when building on Ubuntu host)

**Comment by damianloew** [comment]
> > > > I think that `SYSPAGE` could be removed, but not necessarily within this PR
> > > 
> > > 
> > > `SYSPAGE` is needed if you want to modify syspage, eg. build ia32-generc-qemu with serial UART instead of `vga` (you need to pass `CONSOLE=serial SYSPAGE='psh pc-ata uart16550' TARGET=ia32-generic-qemu`).
> > > Please don't remove anything.
> > 
> > 
> > > uart16550
> > 
> > 
> > It seems that it's deprecated and no longer needed thanks to:
> > https://github.com/phoenix-rtos/phoenix-rtos-project/blob/3cdb486e4276b9ac1fa8ff88e840c38d6939b665/_targets/build.project.ia32-generic#L65
> > 
> > Please correct me if I am wrong (setting CONSOLE=serial is sufficient when building on Ubuntu host)
> 
> I stand corrected, not needed in this particular use case. Still, `SYSPAGE` variable is externally configurable on ia32 so it should be possible to configure it in docker-wrapped build (and would probably be configurable for other targets like riscv64 when it would be CI-enabled).
> 
> Please note that CI explicitly sets `SYSPAGE` env variable so if you want to redo it locally 1:1, you should set it also:
> 
> https://github.com/phoenix-rtos/phoenix-rtos-project/blob/3cdb486e4276b9ac1fa8ff88e840c38d6939b665/.github/actions/phoenix-build/action.yml#L35-L41

Yeah, I think the best solution would be to leave passing SYSPAGE in this script and in our build action (in the future it may be needed), but we can remove setting `'psh pc-ata uart16550'` from workflows as it's not necessary. Do you approve such approach?

**Pull request merged**
