### PR TITLE
add mbedtls and azure sdk to ports config

### PR DESCRIPTION
**Pull request by damianloew**
## Description

 - add mbedtls and azure sdk to ports config

## Motivation and Context

 - JIRA: PD-251

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (ia32-generic-qemu, imxrt106x).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by agkaminski — COMMENTED** [review]
Other platforms don't require `export PORTS_MBEDTLS=n` and `export PORTS_AZURE_SDK=n`?

btw, imho these defines should be considered to be `n` by default (need explicit enable to be enabled), so `=n` config would not be needed. If it's needed than all projects need update with this disable when new `ports` feature becomes available, which is unfortunate

**Comment by damianloew** [comment]
> Other platforms don't require `export PORTS_MBEDTLS=n` and `export PORTS_AZURE_SDK=n`?
> 
> btw, imho these defines should be considered to be `n` by default (need explicit enable to be enabled), so `=n` config would not be needed. If it's needed than all projects need update with this disable when new `ports` feature becomes available, which is unfortunate

I thought that `export PORTS_PORTNAME=n` means that we can enable it if we want to, so I've just added those ports to platforms, where they were tested. Please let me know whether we want to set all ports for all platforms to `n` by default.

Personally, I would prefer leaving some default configuration for the specific target architecture in_`targets` and mentioning there all ports possible to run. Additionally, if we wanted to have some different ports config for specific project/board than the one related to its target architecture this would be placed in `_projects`.

**Comment by nalajcie** [comment]
> Other platforms don't require `export PORTS_MBEDTLS=n` and `export PORTS_AZURE_SDK=n`?
> 
> btw, imho these defines should be considered to be `n` by default (need explicit enable to be enabled), so `=n` config would not be needed. If it's needed than all projects need update with this disable when new `ports` feature becomes available, which is unfortunate

All of the ports are disabled by default only explicitly enabling them would make them build (see https://github.com/phoenix-rtos/phoenix-rtos-ports/blob/b46f4344ad527bf55b6ab3ddfbf81eba7278292c/build.sh#L38).

I think the intention was to highlight that this port is supported for `rt106x` and could be enabled by the user if desired. Still, a comment explaining that should be added ;).

**Comment by agkaminski** [comment]
Yeah, it is as I would like it to be - build only if `=y`, so it's ok.

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
