### PR TITLE
ci: add riscv64-generic-qemu project

### PR DESCRIPTION
**Pull request by mateusz-bloch**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by damianloew — COMMENTED** [review]
How many times have you launched tests on riscv64 during CI? Any fails discovered?

**Comment by mateusz-bloch** [comment]
> How many times have you launched tests on riscv64 during CI? Any fails discovered?

Approximately 25 times without encountering any new failures, except  tests where is needed rootfs and during the psh/auth test

**Comment by damianloew** [comment]
> > How many times have you launched tests on riscv64 during CI? Any fails discovered?
> 
> Approximately 25 times without encountering any new failures, except tests where is needed rootfs and during the psh/auth test

That's nice, so we can merge it. Please only change the commit message to sth like `ci: enable running tests on riscv64-generic-qemu`

**Review by damianloew — APPROVED** [review]
LGTM

**Pull request merged**
