### PR TITLE
_projects: add /tmp ramdisk on big targets

### PR DESCRIPTION
**Pull request by adamgreloch**
JIRA: RTOS-924

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

Any code dependent on `/tmp` being persistent across reboots will be invalid after this change (though such code shouldn't exist in the first place)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [X] Tested by hand on: ia32, armv7a9-zynq7000

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing linter checks and tests passed.
- [X] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by nalajcie — APPROVED** [review]
LGTM for me.

@Darchiv , @agkaminski  do you see any negative impact?

@damianloew It's worth noting that the FS tests usually create temp files in `/tmp`. As we move it to ramdisk, we will stop testing `jffs2` implementation, maybe we entertain the idea of running the same libc fs test in various directories (to cover all FSes in CI).

**Comment by agkaminski** [comment]
> LGTM for me.
> 
> 
> 
> @Darchiv , @agkaminski  do you see any negative impact?
> 
> 
> 
> @damianloew It's worth noting that the FS tests usually create temp files in `/tmp`. As we move it to ramdisk, we will stop testing `jffs2` implementation, maybe we entertain the idea of running the same libc fs test in various directories (to cover all FSes in CI).

Not really, LGTM

**Comment by damianloew** [comment]
> LGTM for me.
> 
> @Darchiv , @agkaminski do you see any negative impact?
> 
> @damianloew It's worth noting that the FS tests usually create temp files in `/tmp`. As we move it to ramdisk, we will stop testing `jffs2` implementation, maybe we entertain the idea of running the same libc fs test in various directories (to cover all FSes in CI).

Thanks for the notification, we use /tmp in resolve path tests, socket tests and one test-stat test case. We will add executing those cases in the another directory and I think we will make it separate in yaml files then (to create various testing campaigns further).

**Comment by Darchiv** [comment]
> @Darchiv , @agkaminski do you see any negative impact?

Nope, LGTM.

**Pull request merged**
